const API_URL = '/admin/';

module.exports = {
    ATTENDEE_CREATE_URL: `${API_URL}attendee/create`,
    ATTENDEE_DELETE_URL: `${API_URL}attendee/delete`,
    ATTENDEE_READ_URL: `${API_URL}attendee/read`,
    GIFT_CREATE_URL: `${API_URL}gift/create`,
    GIFT_DELETE_URL: `${API_URL}gift/delete`,
    GIFT_EDIT_URL: `${API_URL}gift/edit`,
    GIFT_READ_URL: `${API_URL}gift/read`,
    GIFT_SCRAPE_URL: `${API_URL}gift/scrape`,
    IMAGE_CREATE_URL: `${API_URL}image/create`,
    IMAGE_CREATE_THUMB_URL: `${API_URL}image/create/thumb`,
    IMAGE_DELETE_URL: `${API_URL}image/delete`,
    IMAGE_READ_URL: `${API_URL}image/read`,
    IMAGE_UPDATE_URL: `${API_URL}image/update`,
    IMAGE_UPLOAD_URL: `${API_URL}image/upload`,
    IMAGES_CREATE_URL: `${API_URL}images/create`,
    USER_LOGIN_URL: `${API_URL}user/login`,
    CONTENT_CREATE_URL: `${API_URL}content/create`,
    CONTENT_DELETE_URL: `${API_URL}content/delete`,
    CONTENT_READ_URL: `${API_URL}content/read`,
    CONTENT_UPDATE_URL: `${API_URL}content/update`,
    HOOK_CREATE_URL: `${API_URL}hook/create`,
    HOOK_DELETE_URL: `${API_URL}hook/delete`,
    HOOK_READ_URL: `${API_URL}hook/read`,
    HOOK_UPDATE_URL: `${API_URL}hook/update`,
};